CREATE TABLE promotion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE etudiant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(150) NOT NULL,
    promotion_id BIGINT NOT NULL REFERENCES promotion(id)
);

CREATE TABLE session_cours (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre VARCHAR(200) NOT NULL,
    promotion_id BIGINT NOT NULL REFERENCES promotion(id),
    code CHAR(6) NOT NULL,
    ouverture_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expiration_at TIMESTAMP WITH TIME ZONE NOT NULL,
    cloture_at TIMESTAMP WITH TIME ZONE NULL
);
CREATE INDEX idx_session_cours_code ON session_cours(code);

CREATE TABLE presence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES session_cours(id),
    etudiant_id BIGINT NOT NULL REFERENCES etudiant(id),
    source VARCHAR(20) NOT NULL CHECK (source IN ('ETUDIANT', 'FORMATEUR')),
    marquee_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_presence_session_etudiant UNIQUE (session_id, etudiant_id)
);

CREATE TABLE exercice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES session_cours(id),
    auteur_id BIGINT NOT NULL REFERENCES etudiant(id),
    lien VARCHAR(2048) NOT NULL,
    statut VARCHAR(30) NOT NULL CHECK (statut IN ('SANS_RELECTEUR', 'EN_ATTENTE_RELECTURE', 'EN_COURS_RELECTURE', 'RELU')),
    depose_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_exercice_session_auteur UNIQUE (session_id, auteur_id)
);

CREATE TABLE relecture (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercice_id BIGINT NOT NULL UNIQUE REFERENCES exercice(id),
    relecteur_id BIGINT NOT NULL REFERENCES etudiant(id),
    ouverte_at TIMESTAMP WITH TIME ZONE NULL,
    note INTEGER NULL CHECK (note IS NULL OR note BETWEEN 0 AND 20),
    commentaire TEXT NULL,
    rendue_at TIMESTAMP WITH TIME ZONE NULL
);

CREATE TABLE tentative_code (
    etudiant_id BIGINT PRIMARY KEY REFERENCES etudiant(id),
    echecs_consecutifs INTEGER NOT NULL DEFAULT 0,
    bloque_jusqu_a TIMESTAMP WITH TIME ZONE NULL
);
